stages:
  - test
  - deploy

.tests:
  image: mhart/alpine-node:latest
  stage: test
  only:
    changes:
      - src/**/*
      - Samples/**/*
  variables:
    NODE_ENV: "test"

test:
  extends: .tests
  services:
    - docker:dind
  script:
    - npm ci
    - npm run test
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  artifacts:
    name: coverage
    expire_in: 31d
    when: always
    paths:
      - coverage/
      - junit.xml
    reports:
      junit: junit.xml

publish:
  image: mhart/alpine-node:latest
  stage: deploy
  only:
    - tags
  script:
    - echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
    - npm ci
    - npm run build
    - npm publish