stages:
  - prepare
  - test


.tests:
  image: mhart/alpine-node:latest
  stage: test
  dependencies:
    - prepare:deps
  variables:
    NODE_ENV: "test"
  only:
    - master
    - feat-typescript
    - /^renovate\/.*$/

prepare:deps:
  image: mhart/alpine-node:latest
  stage: prepare
  variables:
    NODE_ENV: "test"
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/
  cache:
    key: '$CI_BUILD_REF_NAME'
    paths:
      - 'node_modules/'


test:
  extends: .tests
  services:
    - docker:dind
  script:
    - npm run test
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  artifacts:
    name: coverage
    expire_in: 31d
    when: always
    paths:
      - coverage/
      - junit.xml
    reports:
      junit: junit.xml

